name: Python - Test

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9.x, 3.10.x]

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv wheel
        pipenv install --deploy --dev
    - name: Test with Python ${{ matrix.python-version }}
      run: |
        pipenv run pytest -v